### ISSUE TITLE
Can't get certificate with enabled redirect from domain.com to www.domain.com

### ISSUE THREAD

**Issue by Trysystems** [dokku/dokku-letsencrypt#228] opened 2021-04-03 17:03 UTC
Hello! I'm using dokku redirect plugin. After update to last version of dokku letsencrypt it can't receive certificate for domain and www.domain with enabled redirect. If I remove redirect all works fine.

dokku last version
letsencrypt last version
redirect last version

**Comment by aramboi** [comment] 2021-04-12 19:52
I can confirm this behaviour in my environments as well. If you have a redirect from `example.com` to `www.example.com` the certificate issuing for that domain fails.

Sample log:
```
# dokku letsencrypt:enable example
=====> Enabling letsencrypt for example
-----> Enabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for example...
        - Domain 'www.example.com'
        - Domain 'example.com'
       2021/04/12 19:13:50 No key found for account example@example.com. Generating a P256 key.
       2021/04/12 19:13:50 Saved key to /certs/accounts/acme-v02.api.letsencrypt.org/example@example.com/keys/example@example.com.key
       2021/04/12 19:13:51 [INFO] acme: Registering account for example@example.com
       !!!! HEADS UP !!!!

       Your account credentials have been saved in your Let's Encrypt
       configuration directory at "/certs/accounts".

       You should make a secure backup of this folder now. This
       configuration directory will also contain certificates and
       private keys obtained from Let's Encrypt so making regular
       backups of this folder is ideal.
       2021/04/12 19:13:51 [INFO] [www.example.com, example.com] acme: Obtaining bundled SAN certificate
       2021/04/12 19:13:53 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1234
       2021/04/12 19:13:53 [INFO] [www.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1234
       2021/04/12 19:13:53 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
       2021/04/12 19:13:53 [INFO] [example.com] acme: use http-01 solver
       2021/04/12 19:13:53 [INFO] [www.example.com] acme: Could not find solver for: tls-alpn-01
       2021/04/12 19:13:53 [INFO] [www.example.com] acme: use http-01 solver
       2021/04/12 19:13:53 [INFO] [example.com] acme: Trying to solve HTTP-01
       2021/04/12 19:13:53 [WARN] Received request for domain www.example.com:443 with method GET but the domain did not match any challenge. Please ensure your are passing the Host header properly.
       2021/04/12 19:13:54 [WARN] Received request for domain www.example.com:443 with method GET but the domain did not match any challenge. Please ensure your are passing the Host header properly.
       2021/04/12 19:13:55 [WARN] Received request for domain www.example.com:443 with method GET but the domain did not match any challenge. Please ensure your are passing the Host header properly.
       2021/04/12 19:13:57 [WARN] Received request for domain www.example.com:443 with method GET but the domain did not match any challenge. Please ensure your are passing the Host header properly.
       2021/04/12 19:13:59 [INFO] [www.example.com] acme: Trying to solve HTTP-01
       2021/04/12 19:13:59 [INFO] [www.example.com] Served key authentication
       2021/04/12 19:14:00 [INFO] [www.example.com] Served key authentication
       2021/04/12 19:14:00 [INFO] [www.example.com] Served key authentication
       2021/04/12 19:14:58 [INFO] [www.example.com] Served key authentication
       2021/04/12 19:15:35 [INFO] [www.example.com] The server validated our request
       2021/04/12 19:15:35 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1234
       2021/04/12 19:15:36 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1234
       2021/04/12 19:15:36 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1234
       2021/04/12 19:15:36 Could not obtain certificates:
       	error: one or more domains had a problem:
       [example.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: The key authorization file from the server did not match this challenge "9_TFw63FZV-ekLU90s35sx3kaA1234sE4W2d7dhr39k.crP4SldoRID_1TWF5sxWwU8aTucX52z0Ovz5dvUI894" != "TEST"
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
 !     Failed to setup letsencrypt
 !     Check log output for further information on failure
```
The most interesting part of the above log is the error `[example.com] acme: error: 403` at the end, where the key authorization is getting matched to `TEST`?

Here are the versions of dokku and plugins I am running now:
```
dokku - 0.24.4
letsencrypt - 0.11.8
redirect - 0.6.2
```

**Comment by josegonzalez** [comment] 2021-04-12 19:54
Okay great yeah, just seeing this elsewhere as well. No idea where TEST comes from just yet, but I debugged a similar issue on slack.

Not sure what the best way about this is - ideally we perform the redirects in the core instead of via a plugin, in which case the redirects could be "removed" during the letsencrypt phase? I'll have to think on this a bit...

**Comment by arusa** [comment] 2021-04-12 21:07
Very strange why this hasn't been a problem before.

Maybe you could also solve this by only redirecting requests that don't look like a letsencrypt validation URL. So you don't have to disable and enable the redirect every time.

**Comment by josegonzalez** [comment] 2021-04-12 21:09
I wonder if the redirects that get injected can include extra nginx confs?

**Comment by arusa** [comment] 2021-04-13 07:36
I just had to manually remove 6 redirects from an app before I could run letsencrypt:auto-renew to afterwards manually create those 6 redirects again :-(

And creating the redirects takes incrementally longer every time because creating the last redirect configures all other redirects once again...

It would be really interesting why the validations just worked fine a while ago. Maybe it has something to do with the switch to acme/lego ?

**Comment by josegonzalez** [comment] 2021-04-13 16:44
I don't think it actually ever worked prior to the change to lego. My guess is that partial ssl retrieval was deemed "successful" previously and acme/lego does not allow for partial success. In the previous case, the redirects were swallowing those domains and just not allowing any response.

I pushed a potential fix to the dokku-redirect plugin that includes all the app-specific conf include files, so if you run the following I think it'll be fine:

```shell
dokku plugin:update
dokku proxy:build-config $APP
dokku letsencrypt:auto-renew $APP
```

If someone can confirm that works, the following should fix it for all apps (assuming you have a new enough Dokku install, which I hope you do!):

```shell
dokku plugin:update
dokku proxy:build-config --all
dokku letsencrypt:auto-renew
```

**Comment by josegonzalez** [comment] 2021-04-13 17:18
Alright, the following versions of the plugins should fix the problem, and I've confirmed on my end that they do:

```
dokku 0.24.4+
dokku-redirect 0.6.1+
dokku-letsencrypt 0.11.8+
```

**Comment by josegonzalez** [comment] 2021-04-13 17:29
Aside, some apps may see similar issues with auth not working, with a weird html response in what the log output says happened. The above fix in dokku-core should resolve that, and will be released in 0.24.5 once tests pass (within the next hour).

**Comment by arusa** [comment] 2021-04-13 18:47
In my case `dokku plugin:update` did not update the plugins, but after updating them directly you could solve my problems 🎉 
thanks a lot!

**Comment by ifree92** [comment] 2021-04-14 08:55
I have successfully updated to 0.11.9.
I can confirm the list if working correctly, now I see all enabled apps there and a correct certificate expiration time.

Thanks for that.

**Comment by josegonzalez** [comment] 2021-04-14 10:21
Great, some confirmations are coming in! Closing this issue now.

**Closed by josegonzalez** 2021-04-14 10:21 UTC
