### ISSUE TITLE
Cron job doesn't output error information when errors occur

### ISSUE THREAD

**Issue by jbothma** [dokku/dokku-letsencrypt#195] opened 2020-02-10 07:54 UTC
dokku-letsencrypt version 0.9.1

The cron job doesn't output error information when errors occur, which means we don't get alerted by cron error email (I believe the standard way to be alerted that a cron job failed) when an error occurred.

The following produced no output

    sudo -u dokku /var/lib/dokku/plugins/available/letsencrypt/cron-job

The following produced an error after the usual output

    dokku letsencrypt:auto-renew

the output:

```
=====> Auto-renewing all apps...
-----> municipal-finance needs renewal
=====> Let's Encrypt municipal-finance
-----> Updating letsencrypt docker image...
0.1.0: Pulling from dokku/letsencrypt
Digest: sha256:af5f8529c407645e97821ad28eba328f4c59b83b2141334f899303c49fc07823
Status: Image is up to date for dokku/letsencrypt:0.1.0
       Done updating
-----> Enabling ACME proxy for municipal-finance...
-----> Getting letsencrypt certificate for municipal-finance...
        - Domain 'municipaldata.treasury.gov.za'
        - Domain 'municipalmoney.gov.za'
        - Domain 'www.municipalmoney.gov.za'
        - Domain 'www.municipaldata.treasury.gov.za'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2020-02-10 07:42:03,804:INFO:__main__:1406: Generating new certificate private key
2020-02-10 07:42:08,343:ERROR:__main__:1388: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738103415, https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738103418, https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738103419, https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738103423
Traceback (most recent call last):
  File "/simp_le/simp_le.py", line 1551, in main
    return main_with_exceptions(cli_args)
  File "/simp_le/simp_le.py", line 1535, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le/simp_le.py", line 1456, in persist_new_data
    chain=None,
  File "/simp_le/simp_le.py", line 1124, in persist_data
    plugin.save(new_data)
  File "/simp_le/simp_le.py", line 648, in save
    pems = [self.dump_cert(data.cert)]
  File "/simp_le/simp_le.py", line 468, in dump_cert
    return OpenSSL.crypto.dump_certificate(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

We have used something like [this](https://github.com/OpenUpSA/pombola/blob/master/bin/output-on-error) to print output from a command to stdout/error _only_ if the command exited with a non-zero code as follows:

    0 0 * * 1 dokku --rm run pombola bin/output-on-error bin/backup-data-dir.bash

I see

    dokku letsencrypt:auto-renew

didn't exit with non-zero exit status - does dokku-letsencrypt already output logs if there was a nonzero exit code?

```
...
=====> Finished auto-renewal
ubuntu@dokku9:~$ echo $?
0
```

**Comment by skorokithakis** [comment] 2020-02-26 18:17
I know this issue is about the cron job, but I am getting the exact error above, how did you solve it?

**Comment by genox** [comment] 2020-03-01 09:54
The same applies for CI/CD scenarios basically. I ran into an undetected network issue with one of the dokku apps not using the correct proxy setup, causing letsencrpt to make cert requests over and over again and thus, ending up in the 3 hour ban period without the "build going red". There was no exit code to pick up on.

**Comment by josegonzalez** [comment] 2021-03-23 01:54
I think the problem is that errors are ignored since we're looping, but we should keep track of whether there were _any_ errors.

**Comment by josegonzalez** [comment] 2021-03-23 09:10
Closing as there is a pull request open.

**Closed by josegonzalez** 2021-03-23 09:10 UTC
