### ISSUE TITLE
The plugin has stopped working and returns the following error

### ISSUE THREAD

**Issue by ismardantas** [dokku/dokku-letsencrypt#181] opened 2019-10-02 14:33 UTC
ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by germanp** [comment] 2019-10-10 20:45
Anyone figured out a workaround?

**Comment by nabati** [comment] 2019-10-11 05:15
Any thoughts on a solution @sseemayer or @josegonzalez ?

**Comment by nabati** [comment] 2019-10-11 05:16
I guess this is also a relevant thread with more information related to the issue; https://github.com/dokku/dokku-letsencrypt/issues/147

**Comment by dean1012** [comment] 2019-10-12 02:45
Work was done here @nabati https://github.com/dokku/dokku-letsencrypt/issues/183#issuecomment-541274696

**Comment by josegonzalez** [comment] 2019-10-14 03:00
Duplicate of #183 (and fixed by @dean1012).

**Closed by josegonzalez** 2019-10-14 03:00 UTC

**Comment by germanp** [comment] 2019-10-14 20:52
Thanks, I updated and it works ok.
