### ISSUE TITLE
Feature request: Multiple SSL-Certs for each Domain

### ISSUE THREAD

**Issue by kations** [dokku/dokku-letsencrypt#87] opened 2016-11-26 10:26 UTC
Is it possible to generate a new SSL-Cert for each Domain in a container?

**Comment by sseemayer** [comment] 2016-11-26 15:59
Thanks for your interest in the plugin! This is a duplicate of #48. In short, this would require a change to how certificates in the main dokku project are handled. Since the letsencrypt plugin leaves certificate handling to dokku, I won't be able to do anything about this, sorry. You might find one of the workarounds described in #48 helpful, though

**Closed by sseemayer** 2016-11-26 15:59 UTC
