### ISSUE TITLE
Trouble renewing cert

### ISSUE THREAD

**Issue by blocka** [dokku/dokku-letsencrypt#150] opened 2018-04-15 07:19 UTC
This is what I get
```
$ dokku letsencrypt:auto-renew api
=====> Auto-renew api...
=====> Let's Encrypt api
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for api...
-----> Getting letsencrypt certificate for api...
        - Domain 'api.moves.ouintranet.org'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2018-04-15 07:05:12,543:INFO:__main__:1211: Generating new account key
2018-04-15 07:05:14,796:ERROR:acme.challenges:324: Unable to reach http://api.moves.ouintranet.org/.well-known/acme-challenge/2Oq_ecn_pYl0mo7lnMLKKwljx4_p3A4CtH7ySeHwfg0: HTTPSConnectionPool(host='api.moves.ouintranet.org', port=443): Max retries exceeded with url: /.well-known/acme-challenge/2Oq_ecn_pYl0mo7lnMLKKwljx4_p3A4CtH7ySeHwfg0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
2018-04-15 07:05:14,797:WARNING:__main__:1303: api.moves.ouintranet.org was not successfully self-verified. CA is likely to fail as well!
2018-04-15 07:05:14,890:INFO:__main__:1313: Generating new certificate private key
2018-04-15 07:05:35,457:ERROR:__main__:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/Is5BRB3Hm1aoZvqF9my_MVSc1ZRznwXTQ_TFKKPX6MI
Challenge validation has failed, see error log.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for api...
       done
```

I tried to revoke the certificate and recreate it but I get this:

```
$ dokku letsencrypt:revoke api
=====> Revoke Let's Encrypt certificate from api...
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Revoking letsencrypt certificate for api...
        - Domain 'api.moves.ouintranet.org'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
No existing certificate

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate revocation failed (code 2)!
       done
```

I'm deploying with docker

**Comment by blocka** [comment] 2018-04-26 08:48
thanks for the suggestion. I just wound up migrating to a new server and
dokku version, and everything works not

**Comment by cromulus** [comment] 2018-06-13 19:21
I am having the same issue, stopped the app, tried lets encrypt again, and have the same error.

**Comment by Rigo85** [comment] 2019-05-09 21:55
Hi there, on my dokku server, `dokku letsencrypt app` just stop working, I don't know why!, I have used this command in the same server before and work, not now. The log it's the same as @blocka log. I stppeed and run the command, added the port 5555 on the ports map, and still not working.

**Comment by geeksven-dev** [comment] 2019-08-05 11:51
Having the same issue. Is there anyone with a working solution? Auto renew does not work either. Expired certificates don't work with renew. I have to completely remove the app and recreate it :(

`2019-08-05 11:49:03,363:ERROR:acme.challenges:324: Unable to reach http://ais.smact.group/.well-known/acme-challenge/VVmSPOo1ZpCzzIWdq_XXe5dFN_GANTGk0SQ0hsBgeBk: HTTPSConnectionPool(host='ais.smact.group', port=443): Max retries exceeded with url: /.well-known/acme-challenge/VVmSPOo1ZpCzzIWdq_XXe5dFN_GANTGk0SQ0hsBgeBk (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
2019-08-05 11:49:03,363:WARNING:__main__:1303: ais.smact.group was not successfully self-verified. CA is likely to fail as well!
2019-08-05 11:49:03,584:INFO:__main__:1313: Generating new certificate private key
2019-08-05 11:49:25,064:ERROR:__main__:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/eOH6ndbdQ_gGF6z_GBhEIkkIlzTlyBD_Iv_u-shALBE
Challenge validation has failed, see error log.
`

**Comment by blocka** [comment] 2019-08-05 11:54
Check to make sure you app has a listener on port 80

**Comment by fruitl00p** [comment] 2019-08-05 11:55
@geeksven-dev if you hit the [LE.org url](https://acme-v01.api.letsencrypt.org/acme/authz/eOH6ndbdQ_gGF6z_GBhEIkkIlzTlyBD_Iv_u-shALBE) you'll see the reason for the error from LE's side of things: `Fetching https://ais.smact.group:443/.well-known/acme-challenge/VVmSPOo1ZpCzzIWdq_XXe5dFN_GANTGk0SQ0hsBgeBk: Timeout during connect (likely firewall problem)`. 

Could it be both of you have been running into different port mapping issues?

Could you both (@Rigo85 and @geeksven-dev ) also dump your `proxy:ports` config for both apps? maybe there is a conflict / issue there?

**Comment by geeksven-dev** [comment] 2019-08-05 11:57
For me it looks okay. Or am I missing something crucial?

=====> ais proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:80:5000 https:443:5000

**Comment by fruitl00p** [comment] 2019-08-05 11:58
@geeksven-dev have you tried to disable the `:443` and reissue the LE?

**Comment by geeksven-dev** [comment] 2019-08-05 11:59
I have an idea. Maybe my VM hoster has another firewall in place I can't get accross. And yes a fresh installation always works via vanilla http

**Comment by geeksven-dev** [comment] 2019-08-05 12:26
Okay so far I just tried `dokku certs:remove ais` and then `dokku letsencrypt ais` again. So this makes me pretty sure I have an SSL issue. But I am using the default configurations using vhosts for dokku. And my VM is not guarded by an extra firewall. @fruitl00p do you may have another idea which may cause the failing renewal on port 443?

**Comment by fruitl00p** [comment] 2019-08-05 13:26
@geeksven-dev i'd remove the ssl fully, check the `proxy:ports` and remove any residual `:443`, reload nginx, make sure to clear out all TLS / SSL stuff and reissue 'cleanly'. Also of course make sure that the LE hasn't already blocked due to ratelimiting otherwise you'd be up the creek without a (SSL) paddle ;)

**Comment by Rigo85** [comment] 2019-08-05 13:36
hi there i fixed my issue! https://github.com/dokku/dokku-letsencrypt/issues/172#issuecomment-493524211

**Comment by jfilter** [comment] 2019-08-06 12:44
I second that removing and adding a cert fixes the problem:

`dokku certs:remove myapp && dokku letsencrypt myapp`

**Comment by untoldone** [comment] 2019-09-12 02:14
Just as a heads up for others -- removing the cert and then trying to reinitialize didn't work for me and put me into a state where my app has no valid certs and cannot issue another cert.

**Comment by hovancik** [comment] 2019-11-07 13:23
For me what helped was to restart docker. (And don't forget to update your system while being there ;] )

**Comment by jfilter** [comment] 2020-03-19 19:50
So I finally figured out why I had problems renewing certs. IPv6 was not configured properly. I had an AAAA record for my domain but the VM was not responding to IPv6.

**Comment by pedropazello** [comment] 2020-03-30 14:16
My app had two domains, `www.app.com` and `app.com`.
remove `www.app.com` with `dokku domains:remove app www.app.dorel.com` fix the problem.

**Comment by rsmithlal** [comment] 2020-12-02 20:54
For me, I had to update the letsencrypt plugin itself before the cert renewal would work. I noticed an error fetching the domains for the app, and it worked fine after updating the plugin with `dokku plugin:update letsencrypt` and trying to reissue the cert.

**Comment by josegonzalez** [comment] 2021-03-23 08:27
Going to close this. I think the initial issue was solved, and everyone else is pilling on with something that seems related but probably isn't.

Please open a new issue if you are still having a problem renewing your certificate.

**Closed by josegonzalez** 2021-03-23 08:27 UTC
