### ISSUE TITLE
Reuse accounts between runs

### ISSUE THREAD

**Issue by knyzorg** [dokku/dokku-letsencrypt#251] opened 2022-02-01 21:56 UTC
## Description of problem

This letsencrypt client should implement something similar to #211

### Steps to Reproduce

1. Request a certificate 10 times by running the `letsencrypt:enable` command 10 times
2. Request another within a 3-hour window
 
#### Actual Results

Account is not reused between runs and results in getting locked out for 3 hours from requesting further certificates: https://letsencrypt.org/docs/rate-limits/

> You can create a maximum of 10 Accounts per IP Address per 3 hours. You can create a maximum of 500 Accounts per IP Range within an IPv6 /48 per 3 hours. Hitting either account rate limit is very rare, and we recommend that large integrators prefer a design using one account for many customers. Exceeding these limits is reported with the error message too many registrations for this IP or too many registrations for this IP range.

#### Expected Results

Account is re-used between runs

**Comment by jameysharp** [comment] 2022-03-18 03:14
I think this is a duplicate of #240 and was fixed in #250, which was included in the 0.13.0 release from February 9th. Does that release work for you? I'm not an expert on this plugin, but I wrote the patch in #250 and it seems to work for me.

**Comment by josegonzalez** [comment] 2022-03-18 03:30
Thanks for checking @jameysharp . Would you like commit bit on the repo?

**Comment by josegonzalez** [comment] 2022-03-18 03:31
Closing as I think this is solved based on @jameysharp's work.

**Closed by josegonzalez** 2022-03-18 03:30 UTC

**Comment by chrisjsimpson** [comment] 2022-03-19 23:55
@josegonzalez I don't think it is resolved, this is log output with the @jameysharp patch  (thanks!) https://github.com/dokku/dokku-letsencrypt/pull/250    aplied: (I put a `set -x` on line 182 in `/var/lib/dokku/plugins/available/letsencrypt`:

```
dokku@dokku:~$ dokku letsencrypt:enable example
=====> Enabling letsencrypt for example
-----> Enabling ACME proxy for example..
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for example.com...
        - Domain 'example.com'
++ local 'config=--pem --http --accept-tos --cert.timeout 2592000 --path /certs --server https://acme-v02.api.letsencrypt.org/directory --email alice@example.co.com   --domains example.com'
+++ awk '{print $1}'
+++ sha1sum
+++ echo '--pem --http --accept-tos --cert.timeout 2592000 --path /certs --server https://acme-v02.api.letsencrypt.org/directory --email alice@example.com   --domains example.com'
++ local config_hash=0a4fa3c8860e7e56ee4c3e3e95f0d218b244cfab
++ local config_dir=/home/dokku/example/letsencrypt/certs/0a4fa3c8860e7e56ee4c3e3e95f0d218b244cfab
++ mkdir -p /home/dokku/example/letsencrypt/certs/0a4fa3c8860e7e56ee4c3e3e95f0d218b244cfab
++ echo '--http.port :37286 --pem --http --accept-tos --cert.timeout 2592000 --path /certs --server https://acme-v02.api.letsencrypt.org/directory --email alice@example.com   --domains example.com'
++ echo /home/dokku/example/letsencrypt/certs/0a4fa3c8860e7e56ee4c3e3e95f0d218b244cfab
       2022/03/19 23:46:35 [INFO] acme: Registering account for alice@example.com
       2022/03/19 23:46:35 Could not complete registration
       	acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
 !     Failed to setup letsencrypt
 !     Check log output for further information on failure
 ```

**Comment by josegonzalez** [comment] 2022-03-20 00:07
What version of the plug-in are you using?

**Comment by chrisjsimpson** [comment] 2022-03-20 15:48
> What version of the plug-in are you using?

version = "0.12.1"
```
dokku@dokku:/var/lib/dokku/plugins/enabled/letsencrypt$ pwd
/var/lib/dokku/plugins/enabled/letsencrypt
dokku@dokku:/var/lib/dokku/plugins/enabled/letsencrypt$ cat plugin.toml 
[plugin]
description = "Automated installation of let's encrypt TLS certificates"
version = "0.12.1"
[plugin.config]
dokku@dokku:/var/lib/dokku/plugins/enabled/letsencrypt$
```

Note I manually applied patch https://github.com/dokku/dokku-letsencrypt/pull/250
to test it (that it the only manual patch ever applied to this system)

I note that version [letsencrypt plugin 0.13.0 has recently been released](https://github.com/dokku/dokku-letsencrypt/commit/5370d447e568855e1b72cad07d472ff1bce554c4) so will test that asap too and report back

**Comment by chrisjsimpson** [comment] 2022-03-20 16:12
This is with  letsencrypt plugin  version `0.13.0`: which may suggest account re-registrations are not being reused unless I'm misunderstaning. (Note hours have passed so the rate limit error no longer is being triggered for now)

```
dokku@dokku:~$ dokku letsencrypt:enable example
=====> Enabling letsencrypt for example
-----> Enabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for example...
        - Domain 'example.com'
       2022/03/20 15:53:40 [INFO] acme: Registering account for alice@example.com
       !!!! HEADS UP !!!!
       
       Your account credentials have been saved in your Let's Encrypt
       configuration directory at "/certs/accounts".
       
       You should make a secure backup of this folder now. This
       configuration directory will also contain certificates and
       private keys obtained from Let's Encrypt so making regular
       backups of this folder is ideal.
```

**Comment by jameysharp** [comment] 2022-03-20 16:22
Ah, that's right. Accounts registered from previous versions of the plugin aren't reused, but you should find they're reused in the future now.

@josegonzalez, thanks for offering a commit bit, but I'd really rather have any patches I write reviewed before they're merged anyway. I don't understand Dokku plugins well enough yet.

**Comment by chrisjsimpson** [comment] 2022-03-20 18:17
Thanks @jameysharp :raised_hands: 

>  Accounts registered from previous versions of the plugin aren't reused, but you should find they're reused in the future now.

Yes. This is being observed :partying_face: 

Confirmation:
```
dokku@dokku:~$ dokku letsencrypt:enable example
=====> Enabling letsencrypt for example
-----> Enabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for example...
        - Domain 'example.com'
       2022/03/20 18:10:13 No key found for account alice@example.com. Generating a P256 key.
       2022/03/20 18:10:13 Saved key to /certs/accounts/acme-v02.api.letsencrypt.org/alice@example.com/keys/alice@example.com.key
       2022/03/20 18:10:13 [INFO] acme: Registering account for alice@example.com
       !!!! HEADS UP !!!!
       
       Your account credentials have been saved in your Let's Encrypt
       configuration directory at "/certs/accounts".
       
       You should make a secure backup of this folder now. This
       configuration directory will also contain certificates and
       private keys obtained from Let's Encrypt so making regular
       backups of this folder is ideal.
       2022/03/20 18:10:13 [INFO] [example.com] acme: Obtaining bundled SAN certificate
       2022/03/20 18:10:14 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/89699628490
       2022/03/20 18:10:14 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
       2022/03/20 18:10:14 [INFO] [example.com] acme: use http-01 solver
       2022/03/20 18:10:14 [INFO] [example.com] acme: Trying to solve HTTP-01
       2022/03/20 18:10:14 [INFO] [example.com] Served key authentication
       2022/03/20 18:10:14 [INFO] [example.com] Served key authentication
       2022/03/20 18:10:14 [INFO] [example.com] Served key authentication
       2022/03/20 18:10:14 [INFO] [example.com] Served key authentication
       2022/03/20 18:10:20 [INFO] [example.com] The server validated our request
       2022/03/20 18:10:20 [INFO] [example.com] acme: Validations succeeded; requesting certificates
       2022/03/20 18:10:20 [INFO] [example.com] Server responded with a certificate.
-----> Certificate retrieved successfully.
-----> Installing let's encrypt certificates
-----> Unsetting DOKKU_PROXY_SSL_PORT
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP:  http:1234:1234 http:443:1234 http:80:1234
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP:  http:1234:1234 http:443:1234 http:80:1234 https:443:1234
-----> Configuring example.com...(using built-in template)
-----> Creating https nginx.conf
       Reloading nginx
-----> Configuring example.com...(using built-in template)
-----> Creating https nginx.conf
       Reloading nginx
-----> Disabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Done



##########Re-run (note re-registration is not happening - good) :)

dokku@dokku:~$ dokku letsencrypt:enable example
=====> Enabling letsencrypt for example
-----> Enabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Getting letsencrypt certificate for example...
        - Domain 'example.com'
       2022/03/20 18:12:18 [INFO] [example.com] acme: Obtaining bundled SAN certificate
       2022/03/20 18:12:19 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/89699628490
       2022/03/20 18:12:19 [INFO] [example.com] acme: authorization already valid; skipping challenge
       2022/03/20 18:12:19 [INFO] [example.com] acme: Validations succeeded; requesting certificates
       2022/03/20 18:12:19 [INFO] [example.com] Server responded with a certificate.
-----> Certificate retrieved successfully.
-----> Installing let's encrypt certificates
-----> Unsetting DOKKU_PROXY_SSL_PORT
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP:  http:1234:1234 http:443:1234 http:80:1234
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP:  http:1234:1234 http:443:1234 http:80:1234 https:443:1234
-----> Configuring example.com...(using built-in template)
-----> Creating https nginx.conf
       Reloading nginx
-----> Configuring example.com...(using built-in template)
-----> Creating https nginx.conf
       Reloading nginx
-----> Disabling ACME proxy for example...
       Reloading nginx configuration (via systemctl): nginx.service.
-----> Done
```


###  Other sisunderstandings on my part (I think)

I don't understand/know if acme registrations are per server ip + common name or just the server ip, and this was causing me confusion.
