### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by dastrika** [dokku/dokku-letsencrypt#167] opened 2019-02-08 14:40 UTC
We are running a website https://kuhteilen.ch and on mobile chrome (android) we are getting the message ERR_SSL_VERSION_OR_CIPHER_MISMATCH. We cannot figure out why this happens.

It works fine on chrome (osx), Safari, etc. We are using digitalocean / dokku / letsencrypt for two domains:

https://kuhteilen.ch
https://www.kuhteilen.ch

**Comment by D1ceWard** [comment] 2019-04-05 11:26
Same error on old Android (6.0) default browser...
Working fine with Chrome or with my Android 8.0 phone default browser.

**Comment by D1ceWard** [comment] 2019-04-05 11:41
Found the cause for my case, it's not related to dokku-letsencrypt but to dokku itself.
They recently updated default nginx ssl ciphers and the new one aren't working with old mobile devices (apparently).
So follow this to fix it, but it decrease security for newer browser... 
https://github.com/dokku/dokku/pull/3352#issuecomment-458713476

**Comment by fruitl00p** [comment] 2019-04-05 12:24
FYI: when updating the SSL ciphers et al. my advice would be to use [the mozilla configurator](https://mozilla.github.io/server-side-tls/ssl-config-generator/) as a guide. This works, is updated and provides the best support :)

**Comment by josegonzalez** [comment] 2021-03-23 08:37
Closing as this was an issue with different ciphers than the user wanted (and there should be a way to change these upstream).

**Closed by josegonzalez** 2021-03-23 08:37 UTC

**Comment by wonderer007** [comment] 2022-03-25 23:47
@josegonzalez I have same issue, actually I moved my site from one server to another and started getting this issue

**Comment by wonderer007** [comment] 2022-03-26 13:56
this solution works for me https://github.com/dokku/dokku/pull/3352#issuecomment-458713476
