### ISSUE TITLE
renew wildcard ssl cert 

### ISSUE THREAD

**Issue by luisgarcia1010** [dokku/dokku-letsencrypt#170] opened 2019-04-09 13:29 UTC
I have now issued certificates for my domain _example.com_ and _*.example.com_
when extending the certificate shows an error

```
dokku letsencrypt:auto-renew app
=====> Auto-renew app...
=====> Let's Encrypt app
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for app...
-----> Getting letsencrypt certificate for app...
        - Domain 'example.com'
        - Domain '*.example.com'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2019-04-09 13:25:07,657:INFO:__main__:1211: Generating new account key
ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Wildcard names not supported


Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for app...
       done
```

How can I extend the certificate, if it does not even offer, what record in the DNS should I register?

**Comment by fruitl00p** [comment] 2019-05-03 12:10
Currently, the dokku-letsencrypt plugin doesn't yet support wildcard domains...

**Comment by luisgarcia1010** [comment] 2019-05-03 12:51
> Currently, the dokku-letsencrypt plugin doesn't yet support wildcard domains...

Interestingly, it turns out how wildcard certificate for domains was released then ...

**Comment by fruitl00p** [comment] 2019-05-03 13:15
@luisgarcia1010 the validation for wildcard certificates is only possible thru DNS validation (IIRC) and this isnt supported for this plugin...

**Comment by almereyda** [comment] 2019-09-23 17:30
This is a duplicate of #147 and can therefore be closed.

**Closed** 2019-09-23 18:42 UTC
