### ISSUE TITLE
Update to 0.5.0 applies wrong cert

### ISSUE THREAD

**Issue by enjikaka** [dokku/dokku-letsencrypt#51] opened 2016-04-23 12:57 UTC
Update to 0.5.0 applies wrong cert to some applications. The first application in alphabetical orders cert is applied to these apps.

**Comment by enjikaka** [comment] 2016-04-23 13:16
All apps this occurs for have the -80 in their proxy and upstream settings.

```
upstream saoirse-80 {
  server 172.17.0.11:80;
}
```

```
proxy_pass  http://saoirse-80;
```

**Comment by enjikaka** [comment] 2016-04-23 14:17
This was due to `EXPOSE 80` in my Dockerfiles. Solved it by:

1. Destorying dokku app
2. Creating dokku app
3. Change to use PORT env variable in my apps and remove EXPOSE from Dockerfile
4. Push to dokku
5. Redo letsencrypt from beginning

Trying to remove all nginx configs and pushing without destroying does not work.

I'll keep this open for the folk at dokku to make a comment. This is a huge pain in the ass while updating. Fix it.

**Comment by sseemayer** [comment] 2016-04-23 14:32
Having the app listen on all ports found in EXPOSE commands is the [indended new behavior for Dokku 0.5](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports) - see e.g. dokku/dokku#2028 for a discussion about this.

If you want to override this behavior, the official solution is to a) create a custom nginx config for the app or b) make sure that your app container listens on port 5000 or honors the $PORT environment variable and then remove all EXPOSE statements. 

Closing since this is not a bug with dokku-letsencrypt.

**Closed by sseemayer** 2016-04-23 14:32 UTC
