### ISSUE TITLE
Cannot get certificate: You must set at least one -d/--vhost

### ISSUE THREAD

**Issue by bahmutov** [dokku/dokku-letsencrypt#44] opened 2016-04-05 03:40 UTC
First, great job and great blog post, seems very useful.

I am trying to setup SSL with custom domain dokku running with vhost. 
The app works, I can ping it at `name.apps-my-domain.com`.
I installed both the latest dokku-letsencrypt and tag 0.7.0 and for both got the following

```sh
root@dokku:~# dokku letsencrypt hello
=====> Let's Encrypt hello...
-----> Updating letsencrypt docker image...
latest: Pulling from m3adow/letsencrypt-simp_le
420890c9e918: Already exists 
acbaf1e6012f: Already exists 
5f71a1a2d3dc: Already exists 
Status: Image is up to date for m3adow/letsencrypt-simp_le:latest
       done
-----> Enabling ACME proxy for hello...
-----> Getting letsencrypt certificate for hello...
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
You must set at least one -d/--vhost

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for hello...
       done
```

Running dokku `0.4.14`

**Comment by benjohnson** [comment] 2016-04-05 21:40
I believe this is a duplicate of #43.

**Comment by sseemayer** [comment] 2016-04-06 09:20
Confirmed duplicate of #43 - please check out 15d4a7fb047f0 and let me know if this fixes problems for you!

**Closed** 2016-04-07 15:11 UTC
Labels: bug, duplicate
