### ISSUE TITLE
Error on digital ocean dokku droplet

### ISSUE THREAD

**Issue by jgable** [dokku/dokku-letsencrypt#54] opened 2016-04-26 19:47 UTC
When I install the plugin and try to encrypt an app on a digital ocean droplet running dokku 0.5.4 I get the following error.

```shell
root@dokku-messenger-512mb-sfo1-01:~# dokku letsencrypt isitsunny
=====> Let's Encrypt isitsunny
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
420890c9e918: Already exists 
e4a2ae244258: Already exists 
5c6ac6d1c950: Already exists 
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for isitsunny...
-----> Getting letsencrypt certificate for isitsunny...
        - Domain 'isitsunny.southfacingsoftware.com'
/var/lib/dokku/plugins/enabled/letsencrypt/subcommands/default: line 82: 60: command not found
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
simp_le.py: error: argument --valid_min: invalid int value: ''
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for isitsunny...
       done
```

**Comment by jgable** [comment] 2016-04-26 19:51
Here are some basic reproduce steps:

- Follow the [dokku on digital ocean guide](https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-dokku-application)
- Make sure to check vhosts on initial setup and configure a custom domain
- ssh into machine as root
- install this plugin `dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git`
- Set the email environment variable for your app
- try to encrypt with `dokku letsencrypt myapp`

**Comment by sseemayer** [comment] 2016-04-26 20:15
Did you _just_ install dokku-letsencrypt and landed on version 0.8? If so, I might have broken something in the big refactoring. Please let me know

- Your dokku-letsencrypt version
- The output of `dokku letsencrypt isitsunny` with `dokku trace on` enabled (in a gist or pastebin)
- The output of `dokku config --global` and `dokku config isitsunny`

**Comment by sseemayer** [comment] 2016-04-26 20:18
I think I see what the problem is -- please update dokku-letsencrypt using `dokku plugin:update letsencrypt` and let me know if 4570be84945f7a634315ea0cd8b44e951f9d47a1 fixed things for you!

**Comment by jgable** [comment] 2016-04-26 21:06
👍 Thanks, looks like it's working now.

**Comment by sseemayer** [comment] 2016-04-27 07:19
Glad I could help - thanks for the bug report! :+1:

**Closed by sseemayer** 2016-04-27 07:19 UTC
